"use client"

import { motion } from "framer-motion"
import { X, FileDown, Sparkles } from "lucide-react"

interface AiSummaryProps {
  type: "session" | "all"
  onClose: () => void
}

export function AiSummary({ type, onClose }: AiSummaryProps) {
  // Mock AI-generated content
  const sessionSummary = `
    Main themes from this session:
    
    1. Work stress continues to be a primary concern
    2. Client is experiencing difficulty setting boundaries with colleagues
    3. Sleep patterns have improved with mindfulness practice
    4. Client expressed interest in exploring communication strategies
    
    Recommended focus for next session: Practice assertive communication techniques for workplace scenarios.
  `

  const allSessionsSummary = `
    Progress summary across all sessions:
    
    1. Initial anxiety symptoms have decreased by approximately 30%
    2. Sleep quality has improved significantly since implementing bedtime routine
    3. Work stressors remain consistent but coping strategies are more effective
    4. Client shows increased self-awareness around thought patterns
    5. Mindfulness practice has been inconsistent but beneficial when applied
    
    Treatment trajectory is positive with notable improvements in daily functioning.
  `

  return (
    <motion.div
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
    >
      <motion.div
        className="bg-white rounded-2xl shadow-lg max-w-2xl w-full overflow-hidden"
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: 20, opacity: 0 }}
        transition={{ type: "spring", damping: 25, stiffness: 300 }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between p-4 border-b">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-[#D8B4F0]" />
            <h3 className="font-medium">{type === "session" ? "Session Summary" : "All Sessions Summary"}</h3>
          </div>
          <button onClick={onClose} className="p-1 rounded-full hover:bg-[#f0f0f0]">
            <X className="h-5 w-5 text-[#555]" />
          </button>
        </div>

        <div className="p-6 bg-[#F3EEFF]">
          <pre className="whitespace-pre-wrap font-sans text-[#333]">
            {type === "session" ? sessionSummary : allSessionsSummary}
          </pre>
        </div>

        <div className="flex justify-between items-center p-4 border-t">
          <div className="flex gap-2">
            <button className="flex items-center gap-1 px-3 py-1.5 rounded-xl bg-[#D8B4F0] text-white text-sm">
              <FileDown className="h-4 w-4" />
              <span>Save to Notes</span>
            </button>

            {type === "session" ? (
              <button
                className="flex items-center gap-1 px-3 py-1.5 rounded-xl bg-white border border-[#D8B4F0] text-[#D8B4F0] text-sm"
                onClick={() => {}}
              >
                <span>View All Sessions</span>
              </button>
            ) : (
              <button
                className="flex items-center gap-1 px-3 py-1.5 rounded-xl bg-white border border-[#D8B4F0] text-[#D8B4F0] text-sm"
                onClick={() => {}}
              >
                <span>View Current Session</span>
              </button>
            )}
          </div>

          <p className="text-xs text-[#777]">Generated by AI • Not clinical advice</p>
        </div>
      </motion.div>
    </motion.div>
  )
}

